// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pioabikdvcmsfaskzess.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpb2FiaWtkdmNtc2Zhc2t6ZXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzgzMTQsImV4cCI6MjA3Mzk1NDMxNH0.vzTzXSwo_vE5IMIKmUFfzOFxg5vai2JoCoYklGZpEWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});